### ISSUE TITLE
Passing a vector of RV's to submodel doesn't work

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/GraphPPL.jl#181]
When we create a submodel structure where we initialize all rv's and put them in an array ad hoc before passing to a submodel, we get errors when accessing entries of this variable in the submodel. (Throws a `MethodError` because there is no `check_variate_compatability` implemented for `Vector{NodeLabel}`)

```julia 
    @model function mixed_v(y, v)
        for i in 1:3
            v[i] ~ Normal(0, 1)
        end
        y ~ Normal(v[1], v[2])
    end

    @model function mixed_m()
        v1 ~ Normal(0, 1)
        v2 ~ Normal(0, 1)
        v3 ~ Normal(0, 1)
        y ~ mixed_v(v = [v1, v2, v3])
    end
```

If we explicitly pass a ResizableArray, everything parses:
```julia
    @model function mixed_v(y, v)
        for i in 1:3
            v[i] ~ Normal(0, 1)
        end
        y ~ Normal(v[1], v[2])
    end

    @model function mixed_m()
        v1 ~ Normal(0, 1)
        v2 ~ Normal(0, 1)
        v3 ~ Normal(0, 1)
        v = GraphPPL.ResizableArray([v1, v2, v3])
        y ~ mixed_v(v = v)
    end
```

**Comment by bvdmitri** [comment]
I think we should implement `check_variate_compatability` (fix the name btw, it should be `compatibility` :)) for `AbstractArray`. Casting it to a `ResizableArray` is dangerous since if not used correctly in submodel it may create new variables (unintentionally) + there are tons of other `AbstractArrays` e.g. `Reverse` or `Flattenned` and so on.
